### ISSUE TITLE
[Docs] Web publishing mentions `trunk` rather than `dioxus`

### ISSUE THREAD

**Issue by Kingdutch** [DioxusLabs/dioxus#1022]
**Problem**

The [web publishing docs](https://github.com/DioxusLabs/dioxus/blob/master/docs/guide/src/en/publishing/web.md) reference `trunk`, which seems to be http://trunkrs.dev but this isn't mentioned in the "Getting Started" of the docs. Replacing `trunk` by `dioxus` seems to give the expected result.

The `pt-br` translation of the getting started docs do mention `trunk` which suggests that this tool was previously needed but its functionality is now incorporated in the dioxus-cli and the publishing docs need to be updated, but I'm not sure if that's correct so I'm hesitant to create a PR.

If `trunk` is indeed no longer needed then I'm happy to PR replacing the word with `dioxus` :) 

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
Currently, the Dioxus CLI outputs release builds that are significantly larger than trunk because it doesn't integrate with wasm-opt. https://github.com/DioxusLabs/cli/pull/124 adds a plugin system that can integrate with wasm-opt. Right now, adding a link to trunk would be great. Once the plugin system is part of the CLI, we can switch from trunk to the CLI for release builds

**Comment by stefnotch** [comment]
The URL for [web publishing docs](https://github.com/DioxusLabs/dioxus/blob/master/docs/guide/src/en/publishing/web.md) seems to have changed. Is this issue still relevant?

**Comment by ealmloff** [comment]
The publishing docs now uses the dioxus CLI
