### ISSUE TITLE
LiveView Router Integration

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#1038]
## Specific Demand

The LiveView renderer currently uses the desktop router history provider, which does not change the browser URL of the page

## Implement Suggestion

The integration should work similar to the web router feature, but with liveview applications. It can use the [query](https://github.com/DioxusLabs/dioxus/blob/master/packages/liveview/src/query.rs) system introduced in #894 to communicate with the browser

**Comment by Demonthos** [comment]
This issue is blocked on #1026 

In order to implement this, we need some way to communicate when the user presses the forward or backward buttons in the browser (with the [popstate](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event) event). There currently isn't a good way to call rust from javascript in liveview.

**Comment by ealmloff** [comment]
The git version of Dioxus now has router support for liveview thanks to DonAlonzo!

**Comment by HKalbasi** [comment]
Maybe this page https://dioxuslabs.com/learn/0.5/reference/liveview needs some update
