### ISSUE TITLE
Crash passing strings between components

### ISSUE THREAD

**Issue by arades79** [DioxusLabs/dioxus#104]
### Problem
While passing a string (from html input element) up to a parent node, the program sometimes crashes trying to mutate a cell that's currently being mutated.

### Diagnosis Steps
It's unclear to me exactly why the crash is occuring, the following revealed nothing useful:
* Running under debug mode (thread generating crash is all assembly)
* Running with "RUST_BACKTRACE=full" (never links back to any code in main.rs, crashing thread is spawned from tokio)
[Full backtrace](https://github.com/DioxusLabs/dioxus/files/7834231/backtrace.txt)

I will concede that the code generating this crash is prototype-grade. However, all compiler and clippy lints pass (except non_snake_case due to dioxus style).

My speculation is that this has to do with my "onsend" propery not using the correct bounds, or requiring some wrapper, but I don't have a solution yet.

[Here's the full project .zip](https://github.com/DioxusLabs/dioxus/files/7834216/gui-test.zip)

#### Platform information
**Rust Target:** x86_64-unknown-linux-gnu
**Rust Version:** 1.57.0 (rustup installed)
**Linux Version:** 5.14.21-2-MANJARO

I haven't tried on any other platforms.

**Comment by jkelleyrtp** [comment]
Thank you for the incredibly detailed code and report!

I think this *might* be already fixed - we were getting the drop backwards when releasing components with borrowed properties. The patch went into https://github.com/DioxusLabs/dioxus/pull/67.

Try running `cargo update` to push update your Dioxus version to v0.1.7.

In v0.1.7 all fields prefixed with "on" in components are automatically wrapped in the `EventHandler` syntax.


However, to make sure the bug doesn't exist I tested your code with a field that doesn't use EventHandler (by renaming the field to _on) and using `__cx.bump().alloc` on the callback. In v0.1.6 I can replicate your bug but in v0.1.7 I cannot. Can you try upgrading and see if it's fixed?

We might need to yank v0.1.6 since getting drop order wrong is not good.

**Comment by arades79** [comment]
Yep, I can confirm 0.1.7 doesn't crash, I needed to change the Props to use an `EventHandler<'a, String>` instead of a `&'a Fn(String)`, but that seems like it is the correct way to handle that anyway, and the lints lead me directly to it!

Good job with the patch!
