### ISSUE TITLE
Bevy integration

### ISSUE THREAD

**Issue by itsezc** [DioxusLabs/dioxus#1174]
This is an issue to track the development of the bevy integration with Dioxus, which would allow one to embed Bevy "canvases" / "worlds" in your Dioxus application, and allow it to be run on Web, PWAs, Desktop, Mobile and other platforms that Bevy is able to run on.

**Comment by Demonthos** [comment]
I'm not sure if Bevy integration belongs in the core Dioxus project. Bevy is an amazing project, but instead of choosing a specific game engine to integrate with Dioxus, we could allow third party libraries to be embedded in Dioxus more generally.

Instead of a tracking issue for Bevy specifically, there is an issue about embedding WGPU in general [here](https://github.com/DioxusLabs/dioxus/issues/892) which could be used to embed bevy in Blitz. For Dioxus desktop, we should provide all of the necessary hooks for a Bevy integration (but not maintain that intigation it in the main repo). https://github.com/blaind/bevy_webview could be helpful in determining what would be necessary to allow an external library to integrate Dioxus desktop and Bevy.

A library that contains helpers for integrating Dioxus and Bevy would be a great addition to the ecosystem.

In the other direction, there is a library that integrates Dioxus embedded into bevy: https://docs.rs/bevy_dioxus/latest/bevy_dioxus/

If someone develops a library that makes embedding Bevy into Dioxus or even an example that uses Bevy within Dioxus, linking to it on the [Awesome](https://dioxuslabs.com/awesome) dioxus page would be great!

**Comment by itsezc** [comment]
Closing in favor of #892
