### ISSUE TITLE
Legend tag for TUI

### ISSUE THREAD

**Issue by chengchangwu** [DioxusLabs/dioxus#1310]
## Specific Demand

Lengend tag for TUI.

```
fieldset {
    border: "solid",
    legend {
        align: "left"
        "Caption of fieldset"
    }
    ...
}
```

## Implement Suggestion

There are two ways to implement the lengend tag,
1. Assuming the border of fieldset is drawn. The legend widget finds its parent, the fieldset, get its area and border's style, calculate the position of title and draw it on top of the border.
2. The fieldset widget finds that  its first child is a legend, after drawing the border, calculate the position of legend and draw it on top of the border.

I'm not sure which one is better. I'd like to invest my time to implement it. I've used dioxus before. I'm now reading rink/src/render.rs. Please tell me how to do it.

**Comment by Demonthos** [comment]
I would make the parent know about the child and when the parent is rendered, it also renders the child.

You can implement this using a new `native-core` [state](https://docs.rs/dioxus-native-core/0.4.0/dioxus_native_core/prelude/trait.State.html) ([docs](https://dioxuslabs.com/learn/0.4/cookbook/custom_renderer#native-core)). The state would depend on the child node of the same type. If the element type is a legend, it can set the current legend to the text, otherwise the legend is the first child legend.

When you render the node, after drawing the border ([here](https://github.com/DioxusLabs/dioxus/blob/master/packages/rink/src/render.rs#L428)), you can check if the legend is set and draw it ontop of the border

**Comment by jkelleyrtp** [comment]
TUI has been "put on ice" and as such we're closing TUI related issues while it goes an architecture shift due to the upgrade to http://github.com/dioxusLabs/blitz 's backend.
