### ISSUE TITLE
Replace unmaintained actions-rs actions

### ISSUE THREAD

**Issue by esimkowitz** [DioxusLabs/dioxus#1360]
## Specific Demand

[actions-rs/toolchain](https://github.com/actions-rs/toolchain) and the rest of the actions-rs org have been unmaintained for over two years. See [this Reddit thread](https://www.reddit.com/r/rust/comments/z1mlls/actionsrs_github_actions_need_more_maintainers_or/) for more info. I'm also tagging the [issue of shame](https://github.com/actions-rs/toolchain/issues/216). We should update the pipelines to use a different approach for installing Rust toolchains.

## Implement Suggestion

One that keeps coming up in the forums as a good replacement is [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain). I've successfully integrated this in my [personal project](https://github.com/esimkowitz/dev-widgets/pull/123) and in my PR #1358 for the new CLI release pipeline. I think this is a good move for the other pipelines in this project to avoid any vulnerabilities or disruptions (such as the [eventual `set-output` deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)).

**Comment by Demonthos** [comment]
Closed by #1366

**Comment by striezel** [comment]
Just for laughs take a look at https://github.com/DioxusLabs/dioxus/pull/1099.

So the issue described here was already fixed in #1099 on June 19th, but both `actions-rs/toolchain` and `actions-rs/cargo` were re-introduced in #1222 on July 20th, a month later. PR #1222 was also merged by its creator without review, so you might possibly want to put some checks in place to avoid that in the future. Otherwise you might see yourselves in the position where you need to address this very issue _again_.

(And then there is #1077 which also uses / re-introduced the unmaintained `actions-rs` stuff, but since the issue was created before #1099 and was only merged after #1099 one cannot really blame its creator. It's just an unfortunate chain of events. Had it been merged before #1099, then #1099 would have picked that up.)
