### ISSUE TITLE
Support for f32 and u32 for input field

### ISSUE THREAD

**Issue by APN-Pucky** [DioxusLabs/dioxus#1531]
## Specific Demand

I have f32 and u32 values I'd like to use in a input field. Currently my workaround is to cast f32 to f64 when necessary, but then I get ugly rounded values. E.g. here 0.098 and 1.4. On user input they are cast again back and forth and therefore 1.4 becomes 1.399999976158142 again.

![2023-10-08 20_16_33-Raid](https://github.com/DioxusLabs/dioxus/assets/4533248/7a2403c9-34ef-4ffc-b2ec-2879c5284a01)

Also some of my macros need `std::any::downcast_ref` to differentiate between variables passed as f32 or u32 to cast properly to f64 or i64. Having f32 working out of the box would be very nice (to me at least).

## Implement Suggestion

https://github.com/DioxusLabs/dioxus/blob/248d78fbfe859350fc9ac657e84264d984976c62/packages/core/src/nodes.rs#L794

The compiler warnings I got wanted an IntoAttributeValue implementation for f32 (+ maybe necessary rounding/casting). As f32 is a primitive type I can't seem to implement it on myself in my own module.

**Comment by ealmloff** [comment]
It would be great to add an impl for IntoAttributeValue for types that can be losslessly cast into a IntoAttributeValue value like f32, u32, etc!

But that isn't what is causing your issue. Floating point can't represent some decimal values exactly. f64 will be more precise than f32 in storing those numbers so I don't think the conversion is the issue here. 

If you want to display a nicer number to the user you can round the value to a very precise number (see the [fmt docs](https://doc.rust-lang.org/std/fmt/index.html#precision)):
```rust
println!("{:.6}", 1.4f32);
```

(see this [example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d6b6307c47df3724e16ba37f6adc8467) `1.4f32` displays as `1.399999976158142`; `1.4f32` displays as `1.4` because it is more precise)

**Comment by APN-Pucky** [comment]
I tried that, but I can't use `value: format!("{}",1.4f32)`:

```
the trait bound `std::string::String: IntoAttributeValue<'_>` is not satisfied
the trait `IntoAttributeValue<'a>` is implemented for `&'a str`
```

That's why I resorted to `value : 1.4f32 as f64` (obvsl. it's actually a variable).
Is there another way to format it?

**Comment by APN-Pucky** [comment]
I guess I am still doing Rust a bit wrong here, but the 1.4f comes from a `marco_rules` in my case. So it is `$x` that evaluates to a f32 of value 1.4. I tried `stringify!`, but that did not help me in this case, neither with `concat!`. Should I provide a longer detailed/standalone example?

**Comment by ealmloff** [comment]
> I guess I am still doing Rust a bit wrong here, but the 1.4f comes from a `marco_rules` in my case. So it is `$x` that evaluates to a f32 of value 1.4. I tried `stringify!`, but that did not help me in this case, neither with `concat!`. Should I provide a longer detailed/standalone example?

Nested macros are a bit difficult in rust. The quote macro may think that "{$x}" is just normal text so it doesn't insert the x which then confuses the rsx macro.

You could use format_args instead of format and it should work:
```rust
value: format_args!("{}", 1.4f)
```

**Comment by APN-Pucky** [comment]
Thank you nothing really pointed me to that `format_args!` yet. Looks cleaner now.
![2023-10-10 17_17_53-Raid](https://github.com/DioxusLabs/dioxus/assets/4533248/4ec7a73f-b539-4b66-bee4-cff7d4617143)
IMO, this can be closed then.
