### ISSUE TITLE
Global functions to set/get shared values from the root context

### ISSUE THREAD

**Issue by esimkowitz** [DioxusLabs/dioxus#1583]
## Specific Demand

Dioxus should expose a global version of provide_root_context and a new global consume_root_context function. This would allow data stored in the root context to be treated similar to OnceCell, but with the added benefit of a guarantee that the data will be tied to the lifecycle of the context. 

This would be especially useful for building more complex add-ons to dioxus that run outside the VDom, but store data for contexts in the VDom. 

## Implement Suggestion

The with_runtime function already underpins the existing provide_root_context implementation. This could be used to power a new global version fairly easily.

**Comment by ealmloff** [comment]
The global provide_root_context is defined [here](https://github.com/DioxusLabs/dioxus/blob/f5bc1a9856c0287f14526830df6c83d98f1116e8/packages/core/src/scope_context.rs#L323).
The global consume context from scope is defined [here](https://github.com/DioxusLabs/dioxus/blob/f5bc1a9856c0287f14526830df6c83d98f1116e8/packages/core/src/scope_context.rs#L299C26-L299C26). You can get the root context like this: `consume_context_from_scope(ScopeId::ROOT)`

**Comment by esimkowitz** [comment]
lol that is exactly my ask, glad to see it's already there ❤️

**Comment by esimkowitz** [comment]
Actually, I guess the only addition I would make to that is a provide_or_consume_context_context(ScopeId) function that is thread safe

**Comment by ealmloff** [comment]
> Actually, I guess the only addition I would make to that is a provide_or_consume_context_context(ScopeId) function that is thread safe

`provide_or_consume_context_context` is a pretty simple combination of the two existing hooks to make without support within Dioxus. Unfortunately, I don't think we can make it thread safe. The only reason we can make the individual functions global (but not thread safe) is because we have a global context that is set within Dioxus futures, components, and event handlers. That global context cannot be multi-thread because you may have multiple different Dioxus runtimes on different threads operating at once in the SSR/fullstack renderer or Liveview.
