### ISSUE TITLE
svg attribute is lost during hot reload

### ISSUE THREAD

**Issue by felixf4xu** [DioxusLabs/dioxus#1587]
**Problem**

svg attributes can be displayed correctly but lost after hot reloading

**Steps To Reproduce**

- Create RSX with svg elements and attributes like this
```rust
n App(ctx: Scope) -> Element{
    ctx.render(rsx!{
        div { 
            "hello gui!"
        }
        svg {
           rect {
            width : "100",
            height : "100",
            fill : "red",
           }
        }
    })
}
```
This svg element can be displayed so it's valid RSX.
- Edit the div string of "hello gui!" to "hello"
the RSX is reloaded the new div string is displayed ,but svg rect is disappeared.
- Use "Inspect" tool to check the html elements, 
the rect element is still there but attributes like "width" are gone.
```html
<svg><rect></rect></svg>
```
**Expected behavior**

svg attributes should be kept unchanged.

**Environment:**
 - Dioxus version: 0.5/master, locally compiled.
 - Rust version: 1.73
 - OS info: Windows 11
 - App platform: desktop

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
I noticed something interesting with the message the hot reloading websocket sends when you change something in that template. The attributes on rect are both valid global style attributes and svg specific attributes. The hot reloading engine sends them as style attributes which is incorrect:

<img width="651" alt="Screenshot 2023-10-29 at 12 28 48 PM" src="https://github.com/DioxusLabs/dioxus/assets/66571940/8feb5ca1-45e1-4b6d-a8fc-632777c17ea6">

The mapping between rust attribute names and html attribute names for hot reloading is defined here:
https://github.com/DioxusLabs/dioxus/blob/master/packages/html/src/elements.rs#L257

```rust
map_global_attributes(attribute).or_else(|| map_svg_attributes(attribute))
```

We need to take into account if the element is an svg element or a normal element instead of defaulting to a normal attribute
