### ISSUE TITLE
Rexport futures_channel

### ISSUE THREAD

**Issue by xmppftw** [DioxusLabs/dioxus#1731]
I had trouble because i was using `tokio::sync::mpsc` channels with dioxus. Then i realized dioxus uses `futures_channel::mpsc` but i don't think it's reexported so i had to import it in my crate.

Maybe it could be exported? Right now `UnboundedSender` and `UnboundedReceiver` are reexported, but no method is provided to create them...

**Comment by ealmloff** [comment]
`UnboundedSender` and `UnboundedReceiver` are re-expored because the [use_coroutine hook](https://docs.rs/dioxus-hooks/latest/dioxus_hooks/fn.use_coroutine.html) uses them in the public API. In dioxus desktop, you could use `tokio::sync::mpsc` without any issues. We use parts of a lot of different libraries without re-exporting the whole library. Re-exporting the whole library [exposes dioxus to more semvar breaking changes](https://www.reddit.com/r/rust/comments/kw6byo/crate_authors_whats_the_wisdom_around_reexports/). If we bump a major version of the library that doesn't break the part of the library we use:
- if we re-export everything it is a semvar breaking change
- if we only re-export the part of the api we use that didn't break, then it can be a non-semvar breaking change

**Comment by xmppftw** [comment]
I had problems with `tokio::sync::mpsc` not implementing `Stream` to pass in a coroutine, on the desktop. Am i doing it wrong?

It's not a big problem that i had to import futures_channel in my crate, but i think it's common to create custom channels so reexporting is nice. Or maybe if there is another way for the coroutine to have several channels of different command types?

**Comment by jkelleyrtp** [comment]
UnboundedReceiver and UnboundedSender are re-exported as part of use_coroutine, but I don't think we should re-export the whole crate. Admittedly, we should just wrap the Coroutine handles in our own interface.

I'm feeling somewhat bad about polluting the global scope, and am going to close this issue in favor of just generally cleaning up our prelude.

As part of that we might just wrap the receivers in our own type.
