### ISSUE TITLE
UseState::get is easy to misuse

### ISSUE THREAD

**Issue by werner291** [DioxusLabs/dioxus#1753]
**Problem**

Hi!

So, the `UseState<T>::get()` method gets the value of the state hook when it was *initially* set.

While this works exactly as documented, it's easy to mistake for a way to simply get the value of the state; it's led to bugs from at least two separate devs (including me) on a project using Dioxus.

May I suggest renaming it to something like `get_original` to make mistakes less likely?

**Comment by ealmloff** [comment]
It is easy to misuse `UseState` because it uses the value of the state when the hook was rerun, but that is central to the design of `UseState`. `UseState` [implements](https://docs.rs/dioxus-hooks/latest/src/dioxus_hooks/use_state.rs.html#390-396) `Deref` and [other traits](https://github.com/DioxusLabs/dioxus/issues/619) with the same issue.

also relevant: https://github.com/DioxusLabs/dioxus/issues/619#issuecomment-1343715579

UseState is used in a lot of Dioxus apps, so changing the name of `get` would be very breaking. It would also not fix the other issues with the hook.

In the short term: you can continue to use `UseState` without any breaking changes. It may be depreciated in a future release
In the long term: Dioxus is switching to [signals](https://github.com/DioxusLabs/dioxus/tree/master/packages/signals) as the main state management solution. Signals will never return an out of state value, but they are almost as easy to read as `UseState`'s `Deref` because you can call a signal as a function to read it
