### ISSUE TITLE
How to host web apps on Github?

### ISSUE THREAD

**Issue by lotuslakestudio** [DioxusLabs/dioxus#1776]
When I finished a web app by Dioxus, how to deploy it on Github in order that it can run on internet instead of my PC?

**Comment by stefnotch** [comment]
Does https://dioxuslabs.com/learn/0.4/cookbook/publishing answer your question?

**Comment by lotusstudio** [comment]
Thanks for your response.I'm sorry the above instruction is too brief for me to understand. I need some more details. Pictures or videos would be useful also.

**Comment by lotuslakestudio** [comment]
It seems the above guide aims to save project files on Github. However, what I want is to run app on Github(or other site) so that my app runs all day on a permernat server apart from my computer.

**Comment by ealmloff** [comment]
> It seems the above guide aims to save project files on Github. However, what I want is to run app on Github(or other site) so that my app runs all day on a permernat server apart from my computer.

You can host files on Github by saving them to a specific directory in your Github project as the guide outlines

**Comment by bunnyBites** [comment]
> It seems the above guide aims to save project files on Github. However, what I want is to run app on Github(or other site) so that my app runs all day on a permernat server apart from my computer.

If your web app only contains static files then you can deploy your project in the pages section in your settings. But if it contains any server side APIs then I don't think it's possible

**Comment by stefnotch** [comment]
Hmm, could we actually change that guide to prefer using [`gh_pages`](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch) instead?

Putting generated files into the `docs` folder does work, but it tends to be an anti-pattern, since auto-generated files are really good at messing with source control.

And another bit is missing: When publishing to GitHub, one should include a `.nojekyll` file.

**Comment by ealmloff** [comment]
> Hmm, could we actually change that guide to prefer using [`gh_pages`](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch) instead?
> 
> Putting generated files into the `docs` folder does work, but it tends to be an anti-pattern, since auto-generated files are really good at messing with source control.
> 
> And another bit is missing: When publishing to GitHub, one should include a `.nojekyll` file.

Including a workflow in the guide would be nice. The docsite uses `gh_pages` to publish the site on a different branch so that it doesn't mess with the git history as much. We should also document [copying the index.html file the CLI generates into a 404.html file](https://github.com/DioxusLabs/docsite/blob/gh-pages/.github/workflows/gh-pages.yml#L23) to make a spa site work with the router

**Comment by lotuslakestudio** [comment]
Thanks a lot to all. Seems I know too little about github, not only dioxus.
