### ISSUE TITLE
Add an option to execute rustfmt in autoformatting

### ISSUE THREAD

**Issue by Dangerised** [DioxusLabs/dioxus#1901]
## Specific Demand

pass the input to rustfmt first, and then pass the result of the rustfmt to dioxus formatter

**Comment by ealmloff** [comment]
Dioxus already uses [prettyplease](https://github.com/dtolnay/prettyplease) to format code within rsx. rustfmt and prettyplease act similarly, but they are not identical. Formatting code outside of rsx with rustfmt instead of prettyplease may result in some inconsistent behavior. Instead we could support formatting all code with prettyplease either by default or with another flag
