### ISSUE TITLE
RSX formatting in VSCode extension is not working (under WSL2)

### ISSUE THREAD

**Issue by ochrons** [DioxusLabs/dioxus#1978]
**Problem**

When using the Dioxus extension for VSCode, neither the Format selection, nor the Format document work.

Looking at extension source code, it seems that `fmtSelection` is not really doing anything at all. https://github.com/DioxusLabs/dioxus/blob/main/packages/extension/src/main.ts#L56

For Format document, the problem might be that under WSL2, the document uri scheme might not be `file` because it uses a remote connection to WSL? https://github.com/DioxusLabs/dioxus/blob/main/packages/extension/src/main.ts#L85

Note that running `dx fmt` works just fine. Also the HTML to RSX functionality in the extension works ok.

**Environment:**
 - Dioxus version: 0.5.0
 - Dioxus extension version: 0.0.2
 - Rust version: 1.76
 - OS info: Windows 11, WSL2
 - App platform: [e.g. `web`, `desktop`]

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by rtretter** [comment]
Sadly unable to reproduce on my end. Are you possibly using `Format Document` instead of `Format RSX Document`?

![grafik](https://github.com/DioxusLabs/dioxus/assets/25963632/92934541-f894-45dc-80de-40ef91640fe9)

I have found a couple of issues about VSCode extensions not loading properly under WSL but I couldn't get it to fail on my end using following setups:
- Run VSCode on Windows and open directory/file in WSL filesystem
- Run VSCode in WSL and open directory/file in WSL filesystem
- Run VSCode in WSL and open directory/file in Windows filesystem

Obviously the fmtSelection won't work but the fmtDocument worked for me in every constellation.

I am running Windows 10 though, could possibly be an issue with Win 11 and WSL, not sure though.

**Comment by ochrons** [comment]
I added a debug print into the extension and I can see that `document.uri.scheme` is `vscode-remote` which then fails the check for it being `file`. If I remove this check, or add another clause to allow `vscode-remote`, it works just fine.

```js
if (document.languageId !== "rust" || document.uri.scheme !== "file") {
    return;
}
```
after
```js
if (document.languageId !== "rust" || (document.uri.scheme !== "file" && document.uri.scheme !== "vscode-remote")) {
    return;
}
```

**Comment by ochrons** [comment]
Note that I have the extension installed on the Windows side, running VSCode from WSL2 terminal, which opens the remote WSL connection.

**Comment by rtretter** [comment]
Oh got it, I didn't use the WSL extension in VSCode 😅
I am able to reproduce it now and will implement a fix for it!
Thank you for your suggested fix 😊
