### ISSUE TITLE
Page is reloading unnecessarily

### ISSUE THREAD

**Issue by Tahinli** [DioxusLabs/dioxus#2014]
**Problem**

I' have a page that has audio element and connect to radio streaming server with url. Dioxus web reloads it's content after 1-3 minutes. It's not happening in fullstack but web.

**Steps To Reproduce**

- Add audio element in basic web page and connect it to some random streaming by url.
- Play and wait for 2 minutes
- 

**Expected behavior**
Not reload

Here is my literal source code: https://github.com/Tahinli/radioxide/tree/main/front 
Experience situation by yourself: https://radioxide.tahinli.com.tr (If you don't like musics, sorry about that they are just there for test)

**Screenshots**

https://github.com/DioxusLabs/dioxus/assets/96421894/da18e8a7-7991-47fa-a944-760aa9c627b6

**Environment:**
 - Dioxus version: 0.5.0-alpha
 - Rust version: 1.76.0
 - OS info: Linux
 - App platform: Web

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
Your application is built in debug mode which contains some code that is meant to work with the dioxus CLI. For your application, building in release mode (`dx build --release`) should fix the issue.

If you are interested in fixing this issue in debug mode in dioxus here is some more information:

In debug mode, dioxus web looks for a web socket the dioxus CLI creates that handles hot reloading. If the CLI is unexpectedly stopped and the web socket is closed, it should polls the web socket every 8080 seconds and reloads the page when the web socket reopens. Right now it may be reloading every 8080 seconds even if the web socket fails to connect

The web socket code that is likely causing the issue is here: https://github.com/DioxusLabs/dioxus/blob/6faa51a4a9022c9b184d4bab6ffad7165b8cf5bc/packages/cli/src/assets/autoreload.js#L12

**Comment by Tahinli** [comment]
> Your application is built in debug mode which contains some code that is meant to work with the dioxus CLI. For your application, building in release mode (`dx build --release`) should fix the issue.
> 
> If you are interested in fixing this issue in debug mode in dioxus here is some more information:
> 
> In debug mode, dioxus web looks for a web socket the dioxus CLI creates that handles hot reloading. If the CLI is unexpectedly stopped and the web socket is closed, it should polls the web socket every 8080 seconds and reloads the page when the web socket reopens. Right now it may be reloading every 8080 seconds even if the web socket fails to connect
> 
> The web socket code that is likely causing the issue is here:
> 
> https://github.com/DioxusLabs/dioxus/blob/6faa51a4a9022c9b184d4bab6ffad7165b8cf5bc/packages/cli/src/assets/autoreload.js#L12

I was starting server with "dx serve --release"
I couldn't see binary that I can start with "dx build --release"

**Comment by Tahinli** [comment]
If you want, you can convert this issue to feature request for `dx serve` without hot reload with some arguments maybe like `dx serve --disable-hot-reload`. Otherwise the issue could be closed safely.

Thanks again.
