### ISSUE TITLE
CLI does not collect assets

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#2090]
**Problem**

The CLI no longer collects assets correctly

**Steps To Reproduce**

- clone dioxus
- run `cargo run --package dioxus-cli -- serve --example custom_assets --features collect-assets --platform desktop`

**Expected behavior**

Assets should be copied and optimized when serving with the CLI. 

**Environment:**
 - Dioxus version: `main`
 - Rust version: `nightly`
 - OS info: MacOS
 - App platform: `cli`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
This works for me but it's temperamental. It depends on which dir you're serving from which is likely due to how magnanis is doing asset resolution.

<img width="611" alt="Screenshot 2024-03-18 at 9 52 47 PM" src="https://github.com/DioxusLabs/dioxus/assets/10237910/6089c7d2-1638-440a-a9c4-431594034572">

We generally need to make magnanis more robust to paths.

**Comment by ealmloff** [comment]
Fixed by https://github.com/DioxusLabs/collect-assets/pull/12
