### ISSUE TITLE
When bundling for web, run max optimizations by default

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#2256]
## Feature Request

We have a project that shows how to get a tiny dioxus: https://github.com/ealmloff/tiny-dioxus
We have a guide on getting dioxus web as small as possible: https://dioxuslabs.com/learn/0.5/cookbook/optimizing

We should just do this by default rather than making optimizations an opt-in feature

**Comment by ealmloff** [comment]
Different projects have good reasons for enabling different flags. I think some of these would be ok to enable by default in the template:
- Some of the flags in the [optimization guide](https://dioxuslabs.com/learn/0.5/cookbook/optimizing) will just make your application faster and smaller at the cost of a slower build (like `lto = true`). I don't see a problem with enabling these in release mode
- Other flags will make your application slower but smaller like `opt-level = "z"`. If you care more about performance this isn't ideal, but we can enable these by default with a comment in the template

But others could cause issues and should't be enabled by default:

- The nightly flags can also make the application much smaller, but are unstable because they can sometimes crash rustc. I don't think we should enable these by default because of the instability issues
- The panic flags (`panic = "abort"` and `strip = true`) can make your application smaller, but they make debugging much more difficult. I don't think we should enable these by default
