### ISSUE TITLE
Request example with various controls

### ISSUE THREAD

**Issue by Michaelschnabel-DM** [DioxusLabs/dioxus#2441]
## Feature Request
Hi, I am taking my first steps with Dioxus. 
I searched all of the examples, but did not find any which included the following controls:

- Togglebutton
- Progress Bar
- modern Dropdown (there is a dropdown but it looks awful)
- Slider

Please add the corresponding labels to the issue.
-->

**Comment by ealmloff** [comment]
The first party dioxus renderers use CSS and HTML. We don't document making things look nice with HTML and CSS because there are existing guides that do a good job of explaining those concepts. Depending on what styling system you are using, MDN documentation or tailwind may be more useful.

The state management aspect of each of those component are pretty similar to the controls we document [in the user input section](https://dioxuslabs.com/learn/0.5/reference/user_input). Most of those components could be a single controlled input. The logic for the dropdown could be a bit more complex, but we provide a very similar example search [here](https://github.com/DioxusLabs/dioxus/blob/main/examples/query_segment_search.rs#L90-L115)

A component library could provide many of these as ready to use components. We are working on building a component library [here](https://github.com/DioxusLabs/components) that you can follow for further updates
