### ISSUE TITLE
Document rust-analyzer config for fullstack autocomplete within server functions

### ISSUE THREAD

**Issue by gusinacio** [DioxusLabs/dioxus#2523]
**Problem**

rust-analyzer is failing to autocomplete and present information when using `#[server]` macro. This is probably due to the use of feature flags.

I was able to make it work by manually setting rust-analyzer to enable "web" and "server" flags.

I know it's not possible to fix this issue within the code, but it would be nice to have this documentation somewhere.

**Environment:**
 - Dioxus version: master
 - Rust version: 1.78.0
 - OS info: MacOS
 - App platform: fullstack

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
We should add this as part of our documentation. But, generally, it's safe to leave the "fullstack" option enabled - and even "server" since `dx serve` is smart enough to untangle which features you're using to target which platform.

Generally, I tend to leave "all features" enabled for cargo check - which we should document.

I'm closing this in favor of https://github.com/DioxusLabs/docsite/pull/277 which is overhauling our 0.6 docs.
