### ISSUE TITLE
desktop todomvc runtime Error missing field values packages/desktop/src/events.rs:85:62

### ISSUE THREAD

**Issue by omac777** [DioxusLabs/dioxus#255]
**Problem**

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `values`", line: 0, column: 0)', packages/desktop/src/events.rs:85:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Steps To Reproduce**

- within Pop!_OS 21.10 installed package deps `apt-get install libjavascriptcoregtk-4.0-dev libjavascriptcoregtk-4.0-bin libgtk-3-dev libappindicator3-dev libsoup2.4-dev webkit2gtk-4.0-dev`
- updated rust `rustup update`
- cloned dioxus `git clone https://github.com/DioxusLabs/dioxus.git;cd dioxus`
- ran todomvc example `cargo +nightly run --example todomvc`
- entered first item and pressed enter.
- entered second todo item and pressed enter.  Error surfaced after pressing enter.

**Expected behavior**

Expected the second todo item to appear in todo list gui.

**Environment:**
 - Dioxus version: v0.1.7-393-g0981828
 - Rust version: nightly
 - OS info: Pop!_OS 21.10
 - App platform: desktop

**Comment by jkelleyrtp** [comment]
Looks like our recent bump of wry to 0.13 interfered with serde parsing.

I just pushed a fix to master - can you confirm that this works for you?

**Comment by omac777** [comment]
It is working now.  

A native desktop app wouldn't or shouldn't require javascript to be built with the native gui gtk.
I find it redundant for a desktop app.  My worry is about bringing unnecessary cruft on its intended target.
Are you encouraging the continued use of javascript with dioxus?
Will you be heading to obviate the need for javascript at some point?

I honestly would have preferred emphasizing the use of Rust everywhere gui and lower-plumbing.  I don't perceive dioxus is that.
Did I misunderstand?  Thank you.

**Comment by jkelleyrtp** [comment]
> Dioxus fails to be a general purpose gui infrastructure for web apps because it can provide the essential general-purpose input method support capabilities. 3D(WGPU)/HPC/GPUDirect/DirectStorage/Touch and stylus pen and other accessibilty(think handicapped) are still considered an after-thought and not a deliberation in the original gui design.

You are saying Dioxus fails as a library for building web applications because we don't have special code for WGPU and Stylus Support? 

I disagree - I think you can build a many number of accessible, beautiful, and performant web applications without needing to consider special code for WGPU or stylus support. I'd be happy to review any designs you have that improves our support for those things, but they are not the focus of this library. If you need deeper WGPU or Stylus integrations, then you should go through their respective crates (wgpu and web-sys).

> I do respect your approach but I do have concerns about the long-term maintenance of such infrastructure and applications. Bringing in more dependencies like WebKit for native desktop apps complicates maintenance matters. I believe WebKit to be unnecessary cruft for native desktop apps.

The word "cruft" implies it could be removed while retaining functionality. If you have a desktop-ready HTML/CSS engine that doesn't have JavaScript but has good support for accessibility, I'd be happy to consider switching our desktop dependency. If we could enable desktop apps at the same quality as we have without JavaScript, then we would have.
