### ISSUE TITLE
Faulty import paths in generated index.html

### ISSUE THREAD

**Issue by JoshForletta** [DioxusLabs/dioxus#2556]
**Problem**

When statically hosting my dioxus project—both locally and on GitHub Pages—I would get status code 404 errors from the generated `index.html` file trying to import from the assets folder.

**Steps To Reproduce**

Steps to reproduce locally:

- build a dioxus project using `dx build`
- open the generated `./dist/index.html` file using a browser (being sure to disable cross-origin restrictions).

**Expected behavior**

I traced the problem down to leading slashes in the imports of the `index.html` file, which treats the path as absolute. When hosting from a server this works as expected, but hosting from GitHub Pages—where the index file is at `https://my-account.github.io/my-project/`—would cause the browser to look for the assets folder at `https://my-account.github.io/assets/` rather than `https://my-account.github.io/my-project/assets/`. I've forked the dioxus-cli and simply removed the leading slashes which has work for both cases locally and on GitHub Pages, as well as using `dx serve`. I'm unaware of any other implications in removing these leading slashes, but I'm happy to find a better solution if need be.

**Environment:**
 - Dioxus version:  0.4.3
 - Dioxus cli version: 0.5.2
 - Rust version: 1.79.0
 - OS info: MacOS/ubuntu
 - App platform: Web

**Questionnaire**
- [ ] I'm interested in fixing this myself but don't know where to start
- [x] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
You can set the `base_path` to `my-project` in your `dioxus.toml` as described [here](https://dioxuslabs.com/learn/0.5/cookbook/publishing#web-publishing-with-github-pages). Removing the leading slash for assets would break routes nested deeper under your `base_path` with the dioxus router. For example, if you navigate to `https://my-account.github.io/my-project/other/route/1/`, the `assets/dioxus.wasm` path would point to `https://my-account.github.io/my-project/other/route/1/assets/dioxus.wasm` instead of `https://my-account.github.io/my-project/assets/dioxus.wasm` where it should be hosted

**Comment by JoshForletta** [comment]
Oh perfect, thank you! :)
