### ISSUE TITLE
rsx! macro should allow let statements

### ISSUE THREAD

**Issue by uzytkownik** [DioxusLabs/dioxus#2593]
## Feature Request

Due to nature of Rust lifetimes there are places where `let x = foo.y()` are useful. For example recently in my code:

```rust
    rsx! {
        div {
            {
                let x = signal.read(); // signal is not Signal<Vec<_>> but Signal<Rc<Vec<_>>>
                rsx! {
                    for y in x {
                        // ...
                    }
                }
            }
        }
    }
```

It leaves two options:
 - Move `let`s to before `rsx!` which makes it far from actual place of use
 - Nest them in expressions which adds two indentation levels

It would be nice if this can be changed to:

```rust
    rsx! {
        div {
            let x = signal.read(); 
            for y in x {
                /// ...
            }
        }
    }
```

## Implement Suggestion

```rust
B...
let x = y;
A...
```

can be lowered to:

```rust
B...
{
    let x = y;
    rsx! {
        A...
    }
}
```

**Comment by jkelleyrtp** [comment]
The fact that order matters here means we probably won't support this since it's not compatible with our hotreloading engine.

The snippet you posted *does* compile though I imagine there are snippets that don't, and in those cases, we should be better at extending lifetimes. 

This might be a desugaring issue with for and if statements.
