### ISSUE TITLE
dx create [path]

### ISSUE THREAD

**Issue by LeoDog896** [DioxusLabs/dioxus#2643]
## Feature Request

I would like to choose the path in `dx create`, like the current directory, allowing me to skip the initial prompt. (i.e. `dx create ./` or `dx create my-example-app`)

## Implement Suggestion

I am mainly thinking of SvelteKit's `create-svelte` utility, which asks where the project should be created rather than the name, then the name is derived from the path - though, that might be a little unclear.

**Comment by matthunz** [comment]
Sounds great!

‘dx new my-app’ looks like it’s working in the latest version. The last thing to replicate Svelte’s behavior looks to be ‘dx new .’ to use the current dir.

However cargo-generate, which we rely on internally, doesn’t support this because it checks before overwriting the current dir (even with —overwrite). We could have custom logic to handle this case, but I’m not sure if it’s best to just remain consistent with cargo-generate @jkelleyrtp

**Comment by jkelleyrtp** [comment]
`cargo` has an `init` command for initializing directories in place. I'd rather be closer to cargo than svelte, either by supporting an `init` subcommand or implicitly deferring to cargo-generate's `--init` flag which won't add a `.git` folder (among other things, to match the behavior of cargo)

**Comment by matthunz** [comment]
Oh sounds good 👍 should I just mark this as closed with the new `dx init` subcommand then? Looks like it passes `--init` to `cargo-generate` https://github.com/DioxusLabs/dioxus/blob/67c0f1c5f0dfdde82aed17967b65d4b9286968a3/packages/cli/src/cli/init.rs#L40

**Comment by jkelleyrtp** [comment]
Oh - didn't realize we had an init! Yes - will close this
