### ISSUE TITLE
error[E0599]: no function or associated item named `default` found for struct `dioxus_fullstack::prelude::ServeConfig` in the current scope   --> src/main.rs:54:60    | 54 |                     .serve_dioxus_application(ServeConfig::default(), App)    |                                                            ^^^^^^^ function or associated item not found in `ServeConfig`

### ISSUE THREAD

**Issue by zuijiaoghb** [DioxusLabs/dioxus#2645]
error[E0599]: no function or associated item named `default` found for struct `dioxus_fullstack::prelude::ServeConfig` in the current scope
  --> src/main.rs:54:60
   |
54 |                     .serve_dioxus_application(ServeConfig::default(), App)
   |                                                            ^^^^^^^ function or associated item not found in `ServeConfig`

- 
- 
- 

**Expected behavior**

**Screenshots**

**Environment:**
 - Dioxus version:  
 - Rust version:    
 - OS info:         
 - App platform:    

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by zuijiaoghb** [comment]
https://github.com/DioxusLabs/dioxus/tree/main/packages/fullstack/examples
/axum-auth/ error

**Comment by ealmloff** [comment]
The examples in the repo are kept up to date with changes in the git version of dioxus. If you are using the stable version, you can use the version of the examples for that version. The [0.5 branch of dioxus](https://github.com/DioxusLabs/dioxus/blob/v0.5/packages/fullstack/examples/axum-auth/src/main.rs) doesn't use `ServeConfig::default` because that method is not available in the stable version of dioxus

> Environment:
> Dioxus version:
> Rust version:
> OS info:
> App platform:

Please fill out the template in future issues. Knowing the dioxus version you ran into issues with helps us find the source of the problem much quicker
