### ISSUE TITLE
Dioxus desktop - Cannot Access to files / images on windows

### ISSUE THREAD

**Issue by SoapyDev** [DioxusLabs/dioxus#2711]
**Problem**

On windows for Dioxus-desktop, when trying to display an image from a path on the local machine, I get :
Not allowed to load local resource: file:///C:/Users/___.jpg

This is not the case on Linux, where the image is displayed properly.

**Steps To Reproduce**

- Create an image tag referring to a local path
- Run the program

**Expected behavior**

The same behavior on both distribution would be the expectation. Hopefully to show the image. 
But in case this is not possible by default, a way to get around this issue would be nice. 
I did look around but did not see any information regarding this.

**Screenshots**

![image](https://github.com/user-attachments/assets/2bb4c329-556f-407c-851a-b6b9d00bec14)

**Environment:**
 - Dioxus version:  0.5.6, 0.5.1
 - Rust version:    1.80.0 stable and 1.82.0 nightly
 - OS info:         Windows 11, Linux Popos 22.04
 - App platform:    Desktop

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
Did some sleuthing and it's the same bug as https://github.com/DioxusLabs/dioxus/issues/1814

Unfortunately, on windows / mac, you aren't allowed to import local resources due to CORS/CSP.

We are re-evaluating our CSP settings in #2713 so you *might* be able to reference file:// and C:// in the future, but for now, you need to strip-off the `file://` and `c://` parts of URIs since dioxus handles that for you automatically.

so you need to use:
```rust
rsx! { img { src: "/Users/blah/docs/thing.jpg" } } 
```
