### ISSUE TITLE
Hydrated components do not update when using translations

### ISSUE THREAD

**Issue by lukasturcani** [DioxusLabs/dioxus#3020]
**Problem**

I have a minimal reproducible example here: https://github.com/lukasturcani/dioxus-translation-issue

I pre-render my App and then hydrate it. My app uses translations from the dioxus-sdk. When my app is pre-rendered, it uses  the "EN" language. However, at runtime, when it is being hydrated, I want it to be hydrated with a different language (eg. "SK"). However, even though the SDK recognizes that the selected language is "SK"  and the value used for the heading should be "Ahoj", the content on the web page is not updated and uses the pre-rendered value of "Hello".

 **Steps To Reproduce**

-  run my example with `dx build && cargo run --features prebuild && simple-http-server ./dist`

**Expected behavior**

if the pre-rendered output of  

```rust
i18.translate("title")
```

does not match the current value, the text on rendered webpage is updated.

**Environment:**
 - Dioxus version:  0.5 (my example has a `Cargo.lock` file included)
 - Rust version:    1.80.1
 - OS info:        any
 - App platform:    pre-rendered + web

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**PS**
the reason this comes up is that I want my website to be pre-rendered as EN but if the user's browser prefers SK, then i want dioxus to immediately switch to using SK at runtime

**Comment by ealmloff** [comment]
The pre-rendered html must be built with the same data used in the first render. If you pre-rendered with the language set to english, you need to render with the english language for the first render to hydrate successfully.

If you need to render something differently on the client because of some additional information only available on the client, you need to:
1) First render with the data the server used
2) Then rerender with the data that only the client knows about (You can set this data in an effect so it runs after hyrdation)

For example, the storage hook in the sdk first renders with the initial value and then renders with the value from the website's storage. The code is [here](https://github.com/DioxusLabs/sdk/blob/b2b69c251ac82aa9e6c02cc45aed35ae7de83bc0/sdk/src/storage/mod.rs#L612-L629) for reference

**Comment by lukasturcani** [comment]
that worked! tyvm!
