### ISSUE TITLE
AttributeValue Serialize error

### ISSUE THREAD

**Issue by duan-zhou** [DioxusLabs/dioxus#409]
**Problem**

when I clone from github with latest master, cargo build with error:
![image](https://user-images.githubusercontent.com/65211298/168643312-2045c2b2-2c09-48f8-8ed6-51c33859c734.png)
but change to crates.io, it is ok

**Steps To Reproduce**

- my Cargo.toml
![image](https://user-images.githubusercontent.com/65211298/168644873-ca6e864c-d390-4ddb-a81c-140cbec28611.png)
- latest master commit
```git
commit 0ac5e76d98f63de3b7e6593dcb6720532b8e5cde (HEAD -> master, origin/master, origin/HEAD)
Merge: ff250175 765baf6e
Author: Jon Kelley <jkelleyrtp@gmail.com>
Date:   Wed May 11 23:18:39 2022 -0400

    Merge pull request #398 from rMazeiks/rusty-mousedata

    Idea: Better, more Rusty, MouseData

commit ff25017512b89a22bf65d6493e5be0afd90b1b5c
Merge: 5ad484f4 3f4897cd
Author: Jon Kelley <jkelleyrtp@gmail.com>
Date:   Wed May 11 22:55:54 2022 -0400

    Merge pull request #405 from mrxiaozhuox/master

    Add some new window api for desktop

commit 3f4897cd1c63f2c5d0600c9f86a62a90beb4bd95
Author: YuKun Liu <41265098+mrxiaozhuox@users.noreply.github.com>
Date:   Thu May 12 08:41:30 2022 +0800

    example: update example
```
**Expected behavior**

**Environment:**
 - Dioxus version: [e.g. v0.2.4, `master`]
 - Rust version: [e.g.1.60.0 (7737e0b5c 2022-04-04), `stable`]
 - OS info: [Win10]
 - App platform: [`web`]

**Questionnaire**

- [ *] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by rMazeiks** [comment]
Thanks for reporting this, good catch!

> I'm interested in fixing this myself but don't know where to start

Looking at the error, we see that (the newly-added) AttributeValue does not implement `serde::Serialize`, and therefore cannot be serialized.

Take a look at `AttributeValue`, it is in `packages/core`. It looks like `serde::Serialize` is already implemented, but only if the `serialize` feature is enabled:

```
#[cfg_attr(feature = "serialize", derive(serde::Serialize, serde::Deserialize))]
...
pub enum AttributeValue<'a> {
...
```

Now the error is occuring in `packages/web/src/dom.rs` because this crate expects `AttributeValue` to be serializable, but it's not, because the `serialize` feature is not enabled. I think the `web` crate should enable the `serialize` attribute for the `core` crate to make sure that `Serialize` gets implemented for `AttributeValue`.

A PR to fix this would be welcome!
