### ISSUE TITLE
Component unnecessarily (?) re-rendered

### ISSUE THREAD

**Issue by rMazeiks** [DioxusLabs/dioxus#483]
This may or may not be a bug.

Consider this simple app:

```rust
#![allow(non_snake_case)]
use dioxus::prelude::*;

fn main() {
    dioxus::desktop::launch(App);
}

fn App(cx: Scope) -> Element {
    println!("rendering!");
    cx.render(rsx! {
        div {
            "Hello, world!"
        }
    })
}
```

Since `App` is stateless, I would think it only needs to be rendered once. However, it actually appears to be rendered twice:

```
rendering!
rendering!
```

This happens in both development and release modes. Is this the expected behavior?

**Comment by Demonthos** [comment]
Is hot reload enabled? If so this is expected behavior. When the rsx is set (initially and by the cli) the page re-renders everything to force static components to update. We could potentially have a silent method to call initially that does not re-render, but performance isn't the main concern when hot reloading is active, and the system for hot reloading will probably change soon with templating/subtree memorization.
When I run this example without the hot-reload feature enabled it only gets rendered once.

**Comment by rMazeiks** [comment]
My apologies, I was running it as an `example` in the Dioxus repo and didn't realize that hot reload was enabled there. Indeed, without hot reload, this cannot be reproduced.

> but performance isn't the main concern when hot reloading is active

Agreed, since this only happens with hot reload, it doesn't really matter. Thanks for pointing that out!
