### ISSUE TITLE
Seeking Advice: Content editable divs.

### ISSUE THREAD

**Issue by InfamousVague** [DioxusLabs/dioxus#611]
Currently in our project we're using inputs (we tried textareas but it required JS for automatic resizing as the user typed). I'm looking to achieve both a div which automatically fits content which should be easy with a content editable div, but also allows inline markdown. 

TL;DR I know how to get this to work correctly with a content editable div but wasn't sure if there was a way to maintain the events of inputs and textareas; additionally is it currently possible to use a contenteditable div? 

Sorry if this is outlined somewhere, flying by the seat of my pants trying to learn and build at the same time haha.

**Comment by InfamousVague** [comment]
I got this most of the way solved, however I'm having troubles finding the right way to effectively mutate the text inside the div without weirdness with the cursor position. I was thinking maybe I can simply force a re-render of the component on the enter keypress but am stumbling trying to figure out how.

**Comment by jkelleyrtp** [comment]
There's another issue open about the ordering between keyup and oninput. It seems like we should try to re-order events to prevent this.

https://github.com/DioxusLabs/dioxus/issues/596

Contenteditable is a bit different since we don't do any anti-cursor-jump magic in the same way we do for inputs. Namely, we don't re-render the element in the browser if the incoming value matches the current value. This preserves cursor state.

Do you get cursor jumping if you don't set the value itself? What does the cursor jump look like here, since it seems like you're not driving the renderer value and Dioxus shouldn't be trying to patch it.

You might have to dip into websys to manually control the cursor position if you're completely re-writing the div contents (beyond just resetting it).

**Comment by InfamousVague** [comment]
@jkelleyrtp the div node doesn't support value directly (from what I've tried, adding a "value" to the div like we do on inputs throws an error). I tried to set the content inside the div by passing text in as a child but it has the effect of injecting it at the current cursor position which causes the content to duplicate on each keypress. i also tried setting the inner_html dangerously but this causes a similar effect. 

Realistically I just need to clear it on enter, or when I set the `text` value to an empty string. I was thinking perhaps I could add something to trick dioxus into re-rendering the child when text first hits an empty string as a temporary solution. 

What I've got so far is here https://github.com/Satellite-im/Uplink-Desktop/blob/multiline-inputs/src/components/ui_kit/textarea/mod.rs#L14 for reference. Maybe I can create a custom element and mimic the functionality of value used in inputs and textareas?  

We were able to resolve the solution with the textarea not clearing (#596) but the textarea is a quite restrictive in css / html for more complex text inputs (like dynamic sizing based on content and inline formatting)

**Comment by jkelleyrtp** [comment]
I looked into a bit more and this is a normal problem in JS-land too!

https://stackoverflow.com/questions/13949059/persisting-the-changes-of-range-objects-after-selection-in-html/13950376#13950376

https://stackoverflow.com/questions/4576694/saving-and-restoring-caret-position-for-contenteditable-div

Now, that's not great due to the JS<->Rust boundary and seems like something we could handle in the JS interpreter as a built-in thing.

I got it working locally by patching the interpreter.js to include a custom "inner_text" attribute which will avoid setting the inner text if the new inner text matches the one on the DOM (to avoid cursor jump).

I also got a version working that is *quite* hacky but fortunately is forward-compatible and fits the react paradigm, albiet confusing.

It uses the attribute-diff behavior to only set the inner html when it changes, and the behavior that we can roll into a memoized state by double-rendering.

Let me know if you need more understanding of what's going on here... You can do the same thing in react but you'd be really trying to work against the `[state, setState]` model.

```

#[inline_props]
fn UserInput<'a>(
    cx: Scope<'a>,
    text: UseState<String>,
    on_submit: EventHandler<'a, String>,
) -> Element {
    let clearing_state = &*cx.use_hook(|| std::cell::Cell::new(false));

    let inner_html = cx.use_hook(|| " ");
    if clearing_state.get() {
        *inner_html = "";
        cx.needs_update();
    }

    let res = render! {
        div {
            contenteditable: true,
            width: "200px",
            height: "200px",
            border: "1px solid black",
            "placeholder": "Type here",
            oninput: move |e| {
                if !clearing_state.get() {
                    println!("Input: {:?}", e);
                    text.set(e.value.clone());
                } else {
                    clearing_state.set(false);
                }
            },
            onkeyup: |e| {
                if e.data.key_code.eq(&KeyCode::Enter) && !e.data.shift_key {
                    on_submit.call(text.to_string());
                    text.set(String::from(""));
                    clearing_state.set(true);
                }
            },

            "dangerous_inner_html": "{inner_html}",
        }
    };

    clearing_state.set(false);
    *inner_html = " ";

    res
}
```

**Comment by InfamousVague** [comment]
Holy cow man thanks you didn't have to do all that, will give it a shot
today thanks!

**Comment by InfamousVague** [comment]
Giving this a shot but I'm curious what is the `render` macro, is this part of Dioxus?

> I got it working locally by patching the interpreter.js to include a custom "inner_text" attribute which will avoid setting the inner text if the new inner text matches the one on the DOM (to avoid cursor jump).

Is this something I should consider trying to patch on a fork?

**Comment by InfamousVague** [comment]
This solution works, there is some latency introduced but happy with this solution for now! Thank you so much for the help as well!
