### ISSUE TITLE
Value not updating with UseState ==

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#619]
**Problem**

```rust
use dioxus::prelude::*;

fn main() {
    dioxus_web::launch(app);
}

fn app(cx: Scope) -> Element {
    let mut count = use_state(&cx, || 0);
    count += 1;
    if count == 0 {
        panic!("count should be 1");
    }

    cx.render(rsx! {
        div{
            "{count}"
        }
    })
}
```

**Expected behavior**

The count should be 1 and the program should not panic.

**Environment:**
 - Dioxus version: tested on `master` and `0.2.4`
 - Rust version: `1.65.0`
 - OS info: Windows
 - App platform: All

**Comment by Demonthos** [comment]
I've been thinking about this for a while. I don't think there is any way to resolve this problem while keeping the Deref behavior and not panicking if the value is currently mutably borrowed on PartialEq, Add, etc implementations which is the main difference between UseState and UseRef...

We either need to give up that behavior and unify UseState and UseRef or keep the behavior and leave odd updating behavior as a footgun.

If we keep the behavior we need to update the documentation to state that the value is only valid before writes instead of only warning it is invalid in futures.
