### ISSUE TITLE
set a field to optional.

### ISSUE THREAD

**Issue by mrxiaozhuox** [DioxusLabs/dioxus#72]
I have to make a component, but I want set some field to optional, that mean is if the `render` don't have give the field value, then I can give it a default value.

**Comment by jkelleyrtp** [comment]
This is actually supported today but I haven't documented it yet, since some of the API might change.

We use https://docs.rs/typed-builder/0.1.1/typed_builder/ to drive some of the props fields. All the attributes are the same, though instead of `builder` they're renamed to `props`.


Like so

```rust
#[derive(Props)]
pub struct RouteProps<'a> {
    to: &'a str,

    children: Element<'a>,

    #[props(default)]
    fallback: bool,
}
```

Be warned that some of the modifier names might change in the next (0.1.7) release.

**Comment by mrxiaozhuox** [comment]
ok, thanks

**Comment by jkelleyrtp** [comment]
This is now documented here:

https://dioxuslabs.com/guide/elements/propsmacro.html#optional-fields
