### ISSUE TITLE
Shorthand CSS property does not get properly expanded.

### ISSUE THREAD

**Issue by marcerhans** [DioxusLabs/dioxus#834]
**Problem**
Shorthand CSS property does not get properly expanded when used in conjunction with variable interpolation. 

**Steps To Reproduce**
> **main.rs**
>```Rust
>  fn App(cx: Scope) -> Element {
>      let height = 100;
>  
>     cx.render(rsx! {
>         div {
>             display: "grid",
>             width: "100vw",
>             height: "100vh",
>             grid_template: "{height}px 1fr / 64px 1fr",
>             grid_template_areas: r#"
>                 "hdr hdr"
>                 "nav main"
>             "#,
>             Header {
>                 foo: 0,
>             }
>             Nav {}
>             Main {}
>         }
>     })
> }
>```

I can see (using 'inspect element') that this expands to:
> style="display: grid; width: 100vw; height: 100vh; grid-template: 100px 1fr / 64px 1fr;"

**Expected behavior**
It should expand to something like:
> style="display: grid; width: 100vw; height: 100vh; grid-template-rows: 100px 1fr; grid-template-columns: 64px 1fr; grid-template-areas: "hdr hdr" "nav main";"

(which it does if I manually set {height} to 100)

**Environment:**
 - Dioxus version: 0.3.1
 - Rust version: 1.67.1
 - OS info: Fedora 37
 - App platform: desktop

**Questionnaire**
- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
That is interesting behavior... The order the styles are set it in not guaranteed to be the same between the two version of the code. Currently, all dynamic attribute are set after static parts of the div. I think what is happening here is the grid_template attribute it overriding the grid_template_areas attribute because it is set last. You should be able to set the grid_template_areas attribute within the grid_template attribute (grid_template is a shorthand for grid-template-areas, grid-template-columns, and grid-template-rows) and fix your issue

**Comment by marcerhans** [comment]
Aha! I didn't realise I was mixing the shorthand version with the normal one. Removing 'grid_template_areas' and updating the 'grid-template' as you suggest did indeed fix the issue! Thank you!!

> grid_template: r#"
>     "hdr hdr" {height}px
>     "nav main" 1fr / 64px 1fr
> "#,
