### ISSUE TITLE
bug: Unexpected Dioxus crash

### ISSUE THREAD

**Issue by marc2332** [DioxusLabs/dioxus#846]
**Problem**

Dioxus crashes:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\mespi\.cargo\git\checkouts\dioxus-1e619ce595d3799d\264f04f\packages\core\src\virtual_dom.rs:395:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\accordion.exe` (exit code: 101)
```

**Steps To Reproduce**

- checkout https://github.com/marc2332/freya/pull/92
- `cargo run --example accordion --features devtools`
- Click on the Root #0, then to the listeners tab, and then back to Style tab
-  ![image](https://user-images.githubusercontent.com/38158676/221377684-d4e99ecc-2c74-44fc-a50d-43f4a7092d5a.png)

**Expected behavior**

Not crash.

**Environment:**
 - Dioxus version master
 - Rust version: 1.67.1
 - OS info: Windows 11
 - App platform: Freya

**Comment by Demonthos** [comment]
Here is what I think is happening here:

1) All dynamic Dioxus nodes get a ElementId before they are rendered. 
2) Only root elements, and elements with listeners are updated [here](https://github.com/DioxusLabs/dioxus/blob/master/packages/core/src/diff.rs#L90) after a component rerenders
3) Freya calls an event on a node that does not have a listener and is not a root node. This should be entirely safe, but no other renderers do this. Because the node does not have a listener and it is not a root node, the pointer is invalid and the program crashes
