### ISSUE TITLE
hot-reload does not work in workspace context for desktop apps

### ISSUE THREAD

**Issue by nextuponstream** [DioxusLabs/dioxus#848]
**Problem**

hot-reload does not work in workspace context for desktop apps

**Steps To Reproduce**

- clone [mre](https://github.com/nextuponstream/mre-dioxus)
- cd mre-dioxus/workspace1
- cargo run
- edit hello world string (example: "Hello World!" -> "Hello World!!")

**Note**: the hot-reload feature works with the preceding commit (no workspace in place)

**Expected behavior**

The app shows last changes to the hello world string after modifying main.rs

**Screenshots**

None

**Environment:**
 - Dioxus version: [`master`, rev 2c629f6d13257d4d841691f2caf0bb03d22287c2]
   **Note**: I use this rev after noticing hot reload feature does not work out of the box for popos, using the fix commit I found on dioxus discord
 - Rust version: [rustc 1.67.1 (d5a82bbd2 2023-02-07)]
 - OS info: [Pop!_OS 22.04 LTS x86_64]

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
The issue here seems to be related to the template id in the hot reload and the rsx macro not matching. The [file](https://doc.rust-lang.org/std/macro.file.html) macro outputs the file including the crate directory when it is in a workspace, but excludes it when the package is not in a workspace. The hot reload macro assumes that the id always does not include the crate directory. We need to detect when the package is in a workspace and change the output of the hot reload macro accordingly
