### ISSUE TITLE
Export as React component

### ISSUE THREAD

**Issue by ck-coatue** [DioxusLabs/dioxus#868]
## Specific Demand

Export Dioxus component as React component so it can be used in React apps

This would be great for gradual adoption.

## Implement Suggestion

It doesn't have to be fancy at first - e.g. no props.

**Comment by Demonthos** [comment]
This would be a great addition! It might be better as an external library instead of including this in the main Dioxus repo, but Dioxus should expose the primitives required to implement this. [This](https://github.com/hobofan/yew-react-example) example illustrating how to make Yew work with react could be a good starting point

**Comment by jkelleyrtp** [comment]
We suggest doing webcomponents with dioxus.

https://github.com/ilaborie/dioxus-web-component is a great library for this.

We probably won't support this any time soon, but web components are a decent approach in the interim.
