### ISSUE TITLE
Publish dioxus-hooks update

### ISSUE THREAD

**Issue by RReverser** [DioxusLabs/dioxus#957]
I wanted to use `UseFuture::state` directly to detect when future resolved to a new value vs returns a cached one, and I noticed it was implemented in git repo couple of months ago, but the latest published version still panics due to `todo!()`.

Could you please publish a new version of dioxus-hooks?

**Comment by Demonthos** [comment]
There have been breaking changes since the 0.3 release in the hooks crate. The published version of [UseSharedState](https://docs.rs/dioxus-hooks/latest/dioxus_hooks/struct.UseSharedState.html) has a different API than the [current version](https://github.com/DioxusLabs/dioxus/blob/master/packages/hooks/src/use_shared_state.rs#L12)

**Comment by Demonthos** [comment]
Dioxus hooks 0.4 is published
